[package]
name = "proseforge_core"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"

[dependencies]
bon = "2.3.0"
serde = "1.0.210"
serde_json = "1.0.128"
slotmap = { version = "1.0.7", features = ["serde"] }
ulid = "1.1.3"
