[package]
name = "proseforge_core"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = []

[dependencies]
bon = "2.3.0"
slotmap = { version = "1.0.7", features = ["serde"] }
ulid = "1.1.3"
