[package]
name = "proseforge_filesystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.63"
rfd = "0.14.1"
proseforge_core = { path = "../../core" }
