[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
pf_core = { path = "../../core" }
rusqlite = { version = "0.32.1", features = ["bundled"] }
thiserror = "1.0.63"
rfd = "0.14.1"
sqlite-ulid = "0.2.1"
